@userId=69ac3614119dbcc35e58d5c2
@taskId=69ad56f1e6f19f1fa8020b2c

###

GET {{ baseUrl }}/tasks/{{ taskId }}?userId={{ userId }}

###

GET {{ baseUrl }}/tasks?userId={{ userId }}

###

POST {{ baseUrl }}/tasks?userId={{ userId }}
Content-Type: application/json

{
    "title": "Complete the project"
}

###

PATCH {{ baseUrl }}/tasks/{{ taskId }}?userId={{ userId }}
Content-Type: application/json

{
    "title": "Complete the project 3"
}

###

DELETE {{ baseUrl }}/tasks/{{ taskId }}?userId={{ userId }}


