@userId=69ac3614119dbcc35e58d5c2
@taskId=69ad5d3cc24b966f497f495d

###

POST {{ baseUrl }}/tasks?userId={{ userId }}
Content-Type: application/json

{
    "title": "Complete the project"
}

###

PATCH {{ baseUrl }}/tasks/{{ taskId }}?userId={{ userId }}
Content-Type: application/json

{
    "title": "Complete the project 3"
}

###

DELETE {{ baseUrl }}/tasks/{{ taskId }}?userId={{ userId }}


