@taskId=69ad56f1e6f19f1fa8020b2c
@accessToken=replace-with-access-token

###

GET {{ baseUrl }}/tasks/{{ taskId }}
Authorization: Bearer {{ accessToken }}

###

GET {{ baseUrl }}/tasks
Authorization: Bearer {{ accessToken }}

###

POST {{ baseUrl }}/tasks
Content-Type: application/json
Authorization: Bearer {{ accessToken }}

{
    "title": "Complete the project"
}

###

PATCH {{ baseUrl }}/tasks/{{ taskId }}
Content-Type: application/json
Authorization: Bearer {{ accessToken }}

{
    "title": "Complete the project 3"
}

###

DELETE {{ baseUrl }}/tasks/{{ taskId }}
Authorization: Bearer {{ accessToken }}


