@accessToken=replace-with-access-token

###

POST {{ baseUrl }}/users
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Cena",
    "email": "john.cena@example.com",
    "password": "Password@123"
}

###

GET {{ baseUrl }}/users
Authorization: Bearer {{ accessToken }}

###
PATCH {{ baseUrl }}/users
Content-Type: application/json
Authorization: Bearer {{ accessToken }}

{
    "firstName": "John2",
    "lastName": "Cena2"
}


###

DELETE {{ baseUrl }}/users
Authorization: Bearer {{ accessToken }}

###

GET {{ baseUrl }}/users/all
Authorization: Bearer {{ accessToken }}