@userId=69ac363ddc3346fb89248943

###

POST {{ baseUrl }}/users
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Cena",
    "email": "john.cena@example.com",
    "password": "Password@123"
}

###

GET {{ baseUrl }}/users?id={{ userId }}

###
PATCH {{ baseUrl }}/users?id={{ userId }}
Content-Type: application/json

{
    "firstName": "John2",
    "lastName": "Cena2"
}


###

DELETE {{ baseUrl }}/users?id={{ userId }}