POST {{ baseUrl }}/users
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Cena",
    "email": "john.cena@example.com",
    "password": "Password@123"
}

###

GET {{ baseUrl }}/users?id=69ac2900a1d5ef133b45834a
